version: '3'

# docker pull postgres
# docker pull dpage/pgadmin4
# docker pull papitoio/zombie-api
# docker pull papitoio/zombie-web

services:
  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./pgdb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: zombieplus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qaninja
    networks:
      - skynet

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@qaninja.io'
      PGADMIN_DEFAULT_PASSWORD: 'qaninja'
    ports:
      - '15432:80'
    depends_on:
      - pgdb
    networks:
      - skynet

  zombie_api:
    image: papitoio/zombie-api
    environment:
      DATABASE: 'pgdb'
    ports:
      - '3000:3000'
    depends_on:
      - pgdb
    networks:
      - skynet

  zombie_web:
    image: papitoio/zombie-web
    environment:
      VUE_APP_API: 'http://zombie:3000'
    ports:
      - '5000:5000'
    depends_on:
      - zombie_api
    networks:
      - skynet

networks:
  skynet:
    driver: bridge
