version: '3'

services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins-blueocean
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./.jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - skynet-jenkins

networks:
  skynet-jenkins:
    driver: bridge
